name: Update Posts (dev-news) [Self-hosted]

permissions:
  contents: write

on:
  schedule:
    - cron: '0 3/6 * * *' # every 6 hours starting at 3 AM
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch ("dev-news")'
        required: false
        default: 'dev-news'
        type: string

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  self-hosted:
    uses: ./.github/workflows/update_posts_shared.yaml
    with:
      runner: self-hosted
      target_branch: ${{ inputs.target_branch || 'dev-news' }}
    secrets: inherit
