name: Update Posts (dev-news)

permissions:
  contents: write

on:
  schedule:
    - cron: '0 4,10,16,22 * * *' # 06:00, 12:00, 18:00, 00:00 CEST
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch ("dev-news")'
        required: false
        default: 'dev-news'
        type: string

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4 
        with:
          ref: ${{ inputs.target_branch || 'dev-news' }}
          fetch-depth: 0
          token: ${{ secrets.DEV_LINKS_PAT }}

      - name: Git Config
        run: |
          git config core.fileMode false
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        shell: bash

      - name: Prepare Scripts
        run: |
          # get scripts
          git restore --source origin/${{ github.ref_name }} -- blogs.json
          git restore --source origin/${{ github.ref_name }} -- fix_post_times.js
          git restore --source origin/${{ github.ref_name }} -- gen_news.js
          git restore --source origin/${{ github.ref_name }} -- update_posts.sh
          chmod +x ./update_posts.sh
        shell: bash

      - name: Build
        run: |
          ./update_posts.sh
          node gen_news.js ${{ github.ref_name }}

          # cleanup temp scripts
          rm blogs.json
          rm gen_news.js
          rm update_posts.sh

          git status -s
          git add .
          git diff --cached --quiet --exit-code
          if [ $? -eq 0 ]; then echo "No git changes"; exit 0; fi

          git commit -m "Update posts"
          git push
        shell: bash {0}
