name: Update Posts (dev-news) [GitHub-hosted]

permissions:
  contents: write

on:
  schedule:
    - cron: '0 */6 * * *' # every 6 hours starting at midnight
  workflow_dispatch:
    inputs:
      target_branch:
        description: 'Target branch ("dev-news")'
        required: false
        default: 'dev-news'
        type: string

concurrency:
  group: ${{ github.repository }}
  cancel-in-progress: true

jobs:
  github-hosted:
    uses: ./.github/workflows/update_posts_shared.yaml
    with:
      runner: ubuntu-latest
      target_branch: ${{ inputs.target_branch || 'dev-news' }}
    secrets: inherit
