name: Update Posts (dev-news) [Shared]

permissions:
  contents: write

on:
  workflow_call:
    inputs:
      runner:
        required: true
        type: string
      target_branch:
        required: true
        type: string

jobs:
  update_posts:
    runs-on: ${{ inputs.runner || 'ubuntu-latest' }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.target_branch || 'dev-news' }}
          fetch-depth: 0
          token: ${{ secrets.DEV_LINKS_PAT }}

      - name: Git Config
        run: |
          git config core.fileMode false
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        shell: bash

      - name: Prepare Scripts
        run: |
          # get scripts
          git restore --source origin/${{ github.ref_name }} -- gen_news.js
          git restore --source origin/${{ github.ref_name }} -- update_posts.sh
          chmod +x ./update_posts.sh
        shell: bash

      - name: Build
        run: |
          ./update_posts.sh

          # cleanup temp scripts
          rm gen_news.js
          rm update_posts.sh

          git status -s
          git add .
          git diff --cached --quiet --exit-code
          if [ $? -eq 0 ]; then echo "No git changes"; exit 0; fi

          git commit -m "Update posts"
          git push
        shell: bash {0}
